/* eslint-env mocha */
import assert from 'assert';
import {
  decodeAddress,
  ALGORAND_ADDRESS_LENGTH,
  addressFromPQKey,
} from '../src/encoding/address.js';
import {
  addressWithSignersFromRawFalcon1024Signer,
  Falcon1024SigningKey,
  FALCON_1024_SCHEME,
} from '../src/falcon-signer.js';
import pqPaymentData from './pq_test_data/pqPayment.json';
import pqDelegatedPaymentData from './pq_test_data/pqDelegatedPayment.json';
import pqRekeyedPaymentData from './pq_test_data/pqRekeyedPayment.json';
import pqRekeyedDelegatedPaymentData from './pq_test_data/pqRekeyedDelegatedPayment.json';
import pqMnemonicData from './pq_test_data/pqMnemonic.json';
import { pq25WordMnemonicToSeed } from '../src/mnemonic/mnemonic.js';
import {
  decodeMsgpack,
  signTransactionWithSigner,
  Transaction,
  LogicSigAccount,
  makeLogicSigAccountTransactionSigner,
} from '../src/main.js';
import { PQ_PROGRAM_TAG } from '../src/logicsig.js';
import { concatArrays } from '../src/utils/utils.js';
import { base64ToBytes, hexToBytes } from '../src/encoding/binarydata.js';
import { couldBeCurvePoint } from '../src/utils/ed25519-check.js';
import lsigAddressKat from './pq_test_data/lsig_address_kat.json';

describe('PQ Address', () => {
  it('derives the sender address of a PQ payment from its public key', () => {
    // pqPayment is sent directly from the Falcon auth address, so decoding the
    // transaction yields the address that fromPQKey must reproduce from the
    // public key.
    const txn = decodeMsgpack(
      base64ToBytes(pqPaymentData.txnBlob),
      Transaction
    );
    const publicKey = base64ToBytes(pqPaymentData.signer.pqSigner.pk);

    const { address } = addressFromPQKey(FALCON_1024_SCHEME, publicKey);
    assert.strictEqual(address.toString(), txn.sender.toString());

    // Go's addrAgain check: derivation is deterministic.
    const { address: addrAgain } = addressFromPQKey(
      FALCON_1024_SCHEME,
      publicKey
    );
    assert.ok(address.equals(addrAgain));
    assert.strictEqual(address.toString(), addrAgain.toString());
  });

  describe('address validity', () => {
    it('produces a well-formed, round-trippable address', () => {
      const publicKey = base64ToBytes(pqPaymentData.signer.pqSigner.pk);
      const { address } = addressFromPQKey(FALCON_1024_SCHEME, publicKey);

      const encoded = address.toString();
      assert.strictEqual(encoded.length, ALGORAND_ADDRESS_LENGTH);
      assert.ok(decodeAddress(encoded).equals(address));
    });
  });

  describe('scheme length validation', () => {
    // Port of TestCanonicalPQAddressSaltRejectsInvalidSchemeLength.
    ['', 'x', 'xyz'].forEach((scheme) => {
      it(`rejects scheme ${JSON.stringify(scheme)}`, () => {
        const publicKey = base64ToBytes(pqPaymentData.signer.pqSigner.pk);
        assert.throws(
          () =>
            addressFromPQKey(new TextEncoder().encode(scheme), publicKey)
              .address,
          /invalid PQ scheme length/
        );
      });
    });
  });

  describe('does not require a registered scheme or validated key', () => {
    // Port of TestCanonicalPQAddressSaltDoesNotRequireRegisteredSchemeOrValidatedKey.
    it('derives a deterministic address for an arbitrary scheme and key', () => {
      const scheme = new TextEncoder().encode('x1');
      const publicKey = Uint8Array.of(0xab, 0xcd, 0xef);

      const { address } = addressFromPQKey(scheme, publicKey);
      const { address: addrAgain } = addressFromPQKey(scheme, publicKey);

      assert.ok(address.equals(addrAgain));
    });
  });
});

describe('PQ mnemonic', () => {
  // The mnemonic -> seed -> public key -> address chain is pre-generated by
  // examples/falcon.ts and stored in pq_test_data/mnemonic.json, so this suite
  // exercises mnemonic-based key derivation without depending on falcon-1024.
  it('derives the expected seed from a mnemonic', () => {
    const seed = pq25WordMnemonicToSeed(
      pqMnemonicData.mnemonic,
      FALCON_1024_SCHEME
    );
    assert.deepEqual(seed, base64ToBytes(pqMnemonicData.seed));
  });

  it('derives the expected address from the mnemonic public key', () => {
    const publicKey = base64ToBytes(pqMnemonicData.publicKey);
    const { address } = addressFromPQKey(FALCON_1024_SCHEME, publicKey);
    assert.strictEqual(address.toString(), pqMnemonicData.address);
  });
});

describe('PQ signers', () => {
  it('properly attaches a signature to a transaction', async () => {
    const txn = decodeMsgpack(
      base64ToBytes(pqPaymentData.txnBlob),
      Transaction
    );

    const falconSigningKey: Falcon1024SigningKey = {
      falcon1024PublicKey: base64ToBytes(pqPaymentData.signer.pqSigner.pk),
      falcon1024Signer: async (data: Uint8Array) => {
        assert.deepEqual(data, txn.bytesToSign());

        return base64ToBytes(pqPaymentData.stxn.pqsig.sig);
      },
    };

    const addrWithSigners =
      addressWithSignersFromRawFalcon1024Signer(falconSigningKey);

    const { blob } = await signTransactionWithSigner(
      txn,
      addrWithSigners.txnSigner
    );
    assert.deepEqual(blob, base64ToBytes(pqPaymentData.stxnBlob));
  });

  it('properly attaches a signature to a rekeyed transaction', async () => {
    // The sender of this transaction is a (rekeyed) ed25519 address that
    // differs from the Falcon auth address, so the signer must populate the
    // `sgnr` (authorizing address) field on the signed transaction.
    const txn = decodeMsgpack(
      base64ToBytes(pqRekeyedPaymentData.txnBlob),
      Transaction
    );

    const falconSigningKey: Falcon1024SigningKey = {
      falcon1024PublicKey: base64ToBytes(
        pqRekeyedPaymentData.signer.pqSigner.pk
      ),
      falcon1024Signer: async (data: Uint8Array) => {
        assert.deepEqual(data, txn.bytesToSign());

        return base64ToBytes(pqRekeyedPaymentData.stxn.pqsig.sig);
      },
    };

    const addrWithSigners =
      addressWithSignersFromRawFalcon1024Signer(falconSigningKey);

    const { blob } = await signTransactionWithSigner(
      txn,
      addrWithSigners.txnSigner
    );
    assert.deepEqual(blob, base64ToBytes(pqRekeyedPaymentData.stxnBlob));
  });

  it('properly attaches a signature to a delegated logic sig', async () => {
    const program = base64ToBytes(pqDelegatedPaymentData.signer.lsig);
    const publicKey = base64ToBytes(pqDelegatedPaymentData.signer.pqSigner.pk);

    const { address: authAddress } = addressFromPQKey(
      FALCON_1024_SCHEME,
      publicKey
    );

    const falconSigningKey: Falcon1024SigningKey = {
      falcon1024PublicKey: publicKey,
      falcon1024Signer: async (data: Uint8Array) => {
        // A delegated lsig is signed over the program bytes (prefixed with the
        // PQ program tag and the auth address), not over a transaction.
        assert.deepEqual(
          data,
          concatArrays(PQ_PROGRAM_TAG, authAddress.publicKey, program)
        );

        return base64ToBytes(pqDelegatedPaymentData.stxn.lsig.pqsig.sig);
      },
    };

    const addrWithSigners =
      addressWithSignersFromRawFalcon1024Signer(falconSigningKey);

    const lsigAccount = new LogicSigAccount(program);
    await lsigAccount.signWithSigner(addrWithSigners);

    assert.deepEqual(
      lsigAccount.lsig.pqsig!.sig,
      base64ToBytes(pqDelegatedPaymentData.stxn.lsig.pqsig.sig)
    );

    const txn = decodeMsgpack(
      base64ToBytes(pqDelegatedPaymentData.txnBlob),
      Transaction
    );

    const { blob } = await signTransactionWithSigner(
      txn,
      makeLogicSigAccountTransactionSigner(lsigAccount)
    );

    assert.deepEqual(blob, base64ToBytes(pqDelegatedPaymentData.stxnBlob));
  });

  it('properly attaches a signature to a rekeyed delegated logic sig', async () => {
    // Same as the delegated lsig case, but the transaction sender is a rekeyed
    // account that differs from the lsig (Falcon auth) address, so the signer
    // must populate the `sgnr` field on the signed transaction.
    const program = base64ToBytes(pqRekeyedDelegatedPaymentData.signer.lsig);
    const publicKey = base64ToBytes(
      pqRekeyedDelegatedPaymentData.signer.pqSigner.pk
    );

    const { address: authAddress } = addressFromPQKey(
      FALCON_1024_SCHEME,
      publicKey
    );

    const falconSigningKey: Falcon1024SigningKey = {
      falcon1024PublicKey: publicKey,
      falcon1024Signer: async (data: Uint8Array) => {
        assert.deepEqual(
          data,
          new Uint8Array(
            concatArrays(PQ_PROGRAM_TAG, authAddress.publicKey, program)
          )
        );

        return base64ToBytes(pqRekeyedDelegatedPaymentData.stxn.lsig.pqsig.sig);
      },
    };

    const addrWithSigners =
      addressWithSignersFromRawFalcon1024Signer(falconSigningKey);

    const lsigAccount = new LogicSigAccount(program);
    await lsigAccount.signWithSigner(addrWithSigners);

    assert.deepEqual(
      lsigAccount.lsig.pqsig!.sig,
      base64ToBytes(pqRekeyedDelegatedPaymentData.stxn.lsig.pqsig.sig)
    );

    const txn = decodeMsgpack(
      base64ToBytes(pqRekeyedDelegatedPaymentData.txnBlob),
      Transaction
    );

    const { blob } = await signTransactionWithSigner(
      txn,
      makeLogicSigAccountTransactionSigner(lsigAccount)
    );

    assert.deepEqual(
      blob,
      base64ToBytes(pqRekeyedDelegatedPaymentData.stxnBlob)
    );
  });
});

describe('ed25519 couldBeCurvePoint', () => {
  lsigAddressKat.edwards25519_decode_cases.forEach((testCase) => {
    it(`${testCase.name}`, () => {
      assert.strictEqual(
        couldBeCurvePoint(hexToBytes(testCase.encoding_hex)),
        testCase.decodes_to_edwards25519_point
      );
    });
  });
});
