/* eslint-env mocha */
import assert from 'assert';
import {
  decodeAddress,
  ALGORAND_ADDRESS_LENGTH,
  addressFromPQKey,
} from '../src/encoding/address.js';
import {
  addressWithSignersFromRawFalcon1024Signer,
  Falcon1024SigningKey,
  FALCON_1024_SCHEME,
} from '../src/falcon-signer.js';
import pqTxnData from './pq_test_data/txn.json';
import pqLsigData from './pq_test_data/lsig.json';
import pqRekeyData from './pq_test_data/rekey.json';
import pqAddressData from './pq_test_data/addresses.json';
import pqMnemonicData from './pq_test_data/mnemonic.json';
import { pq25WordMnemonicToSeed } from '../src/mnemonic/mnemonic.js';
import {
  decodeMsgpack,
  signTransactionWithSigner,
  Transaction,
  LogicSigAccount,
  makeLogicSigAccountTransactionSigner,
} from '../src/main.js';
import { PQ_PROGRAM_TAG } from '../src/logicsig.js';
import { concatArrays } from '../src/utils/utils.js';
import { genericHash } from '../src/nacl/naclWrappers.js';

// Falcon public keys used by the address tests are pre-generated (from a
// 48-byte zero-filled seed with only the first byte set, mirroring Go's
// falconPublicKeyForPQAddressTest) and stored in pq_test_data/addresses.json by
// examples/falcon.ts, so this suite doesn't depend on falcon-1024 itself.
function falconPublicKeyForSeedByte(firstSeedByte: number): Uint8Array {
  const tc = pqAddressData.testCases.find(
    (c) => c.firstSeedByte === firstSeedByte
  );
  if (!tc) {
    throw new Error(`no address test vector for seed byte ${firstSeedByte}`);
  }
  return new Uint8Array(Buffer.from(tc.publicKey, 'base64'));
}

describe('PQ Address', () => {
  describe('known answers (canonical salt)', () => {
    // These are the Go known-answer rows whose explicit salt equals the
    // canonical salt for that key, so they are reachable via fromPQKey.
    const testCases = [
      {
        name: 'seed byte 0 (canonical salt 0)',
        firstSeedByte: 0,
        expectedAddress:
          '7ZQ6VZDWW5NECRV3XMW6L7YX743PFC55IEVS4X3GDHIW4NBMYLYTJT4VTA',
      },
      {
        name: 'seed byte 1 (canonical salt 1)',
        firstSeedByte: 1,
        expectedAddress:
          '4X6LFIO4F7WZFXM24J567HAXW4FHXWKGVGPNCA4SMPPAYMZYSHYTB6XXC4',
      },
    ];

    testCases.forEach((tc) => {
      it(`derives the expected address for ${tc.name}`, () => {
        const publicKey = falconPublicKeyForSeedByte(tc.firstSeedByte);

        const { address } = addressFromPQKey(FALCON_1024_SCHEME, publicKey);
        assert.strictEqual(address.toString(), tc.expectedAddress);

        // Go's addrAgain check: derivation is deterministic.
        const { address: addrAgain } = addressFromPQKey(
          FALCON_1024_SCHEME,
          publicKey
        );

        assert.ok(address.equals(addrAgain));
        assert.strictEqual(address.toString(), addrAgain.toString());
      });
    });
  });

  describe('address validity', () => {
    it('produces a well-formed, round-trippable address', () => {
      const publicKey = falconPublicKeyForSeedByte(1);
      const { address } = addressFromPQKey(FALCON_1024_SCHEME, publicKey);

      const encoded = address.toString();
      assert.strictEqual(encoded.length, ALGORAND_ADDRESS_LENGTH);
      assert.ok(decodeAddress(encoded).equals(address));
    });
  });

  describe('scheme length validation', () => {
    // Port of TestCanonicalPQAddressSaltRejectsInvalidSchemeLength.
    ['', 'x', 'xyz'].forEach((scheme) => {
      it(`rejects scheme ${JSON.stringify(scheme)}`, () => {
        const publicKey = falconPublicKeyForSeedByte(0);
        assert.throws(
          () =>
            addressFromPQKey(new TextEncoder().encode(scheme), publicKey)
              .address,
          /invalid PQ scheme length/
        );
      });
    });
  });

  describe('does not require a registered scheme or validated key', () => {
    // Port of TestCanonicalPQAddressSaltDoesNotRequireRegisteredSchemeOrValidatedKey.
    it('derives a deterministic address for an arbitrary scheme and key', () => {
      const scheme = new TextEncoder().encode('x1');
      const publicKey = Uint8Array.of(0xab, 0xcd, 0xef);

      const { address } = addressFromPQKey(scheme, publicKey);
      const { address: addrAgain } = addressFromPQKey(scheme, publicKey);

      assert.ok(address.equals(addrAgain));
    });
  });
});

describe('PQ mnemonic', () => {
  // The mnemonic -> seed -> public key -> address chain is pre-generated by
  // examples/falcon.ts and stored in pq_test_data/mnemonic.json, so this suite
  // exercises mnemonic-based key derivation without depending on falcon-1024.
  it('derives the expected seed from a mnemonic', () => {
    const seed = pq25WordMnemonicToSeed(
      pqMnemonicData.mnemonic,
      FALCON_1024_SCHEME
    );
    assert.deepEqual(
      seed,
      new Uint8Array(Buffer.from(pqMnemonicData.seed, 'base64'))
    );
  });

  it('derives the expected address from the mnemonic public key', () => {
    const publicKey = new Uint8Array(
      Buffer.from(pqMnemonicData.publicKey, 'base64')
    );
    const { address } = addressFromPQKey(FALCON_1024_SCHEME, publicKey);
    assert.strictEqual(address.toString(), pqMnemonicData.address);
  });
});

describe('PQ signers', () => {
  it('properly attaches a signature to a transaction', async () => {
    const txn = decodeMsgpack(
      Buffer.from(pqTxnData.txnBlob, 'base64'),
      Transaction
    );

    const falconSigningKey: Falcon1024SigningKey = {
      falcon1024PublicKey: new Uint8Array(
        Buffer.from(pqTxnData.publicKey, 'base64')
      ),
      falcon1024Signer: async (data: Uint8Array) => {
        assert.deepEqual(data, new Uint8Array(genericHash(txn.bytesToSign())));

        return new Uint8Array(Buffer.from(pqTxnData.txnSig, 'base64'));
      },
    };

    const addrWithSigners =
      addressWithSignersFromRawFalcon1024Signer(falconSigningKey);

    const { blob } = await signTransactionWithSigner(
      txn,
      addrWithSigners.txnSigner
    );
    assert.deepEqual(
      blob,
      new Uint8Array(Buffer.from(pqTxnData.stxnBlob, 'base64'))
    );
  });

  it('properly attaches a signature to a rekeyed transaction', async () => {
    // The sender of this transaction is a (rekeyed) ed25519 address that
    // differs from the Falcon auth address, so the signer must populate the
    // `sgnr` (authorizing address) field on the signed transaction.
    const txn = decodeMsgpack(
      Buffer.from(pqRekeyData.txnBlob, 'base64'),
      Transaction
    );

    const falconSigningKey: Falcon1024SigningKey = {
      falcon1024PublicKey: new Uint8Array(
        Buffer.from(pqRekeyData.publicKey, 'base64')
      ),
      falcon1024Signer: async (data: Uint8Array) => {
        assert.deepEqual(data, new Uint8Array(genericHash(txn.bytesToSign())));

        return new Uint8Array(Buffer.from(pqRekeyData.txnSig, 'base64'));
      },
    };

    const addrWithSigners =
      addressWithSignersFromRawFalcon1024Signer(falconSigningKey);

    const { blob } = await signTransactionWithSigner(
      txn,
      addrWithSigners.txnSigner
    );
    assert.deepEqual(
      blob,
      new Uint8Array(Buffer.from(pqRekeyData.stxnBlob, 'base64'))
    );
  });

  it('properly attaches a signature to a delegated logic sig', async () => {
    const program = new Uint8Array(Buffer.from(pqLsigData.program, 'base64'));
    const publicKey = new Uint8Array(
      Buffer.from(pqLsigData.publicKey, 'base64')
    );

    const { address: authAddress } = addressFromPQKey(
      FALCON_1024_SCHEME,
      publicKey
    );

    const falconSigningKey: Falcon1024SigningKey = {
      falcon1024PublicKey: publicKey,
      falcon1024Signer: async (data: Uint8Array) => {
        // A delegated lsig is signed over the program bytes (prefixed with the
        // PQ program tag and the auth address), not over a transaction.
        assert.deepEqual(
          data,
          new Uint8Array(
            genericHash(
              concatArrays(PQ_PROGRAM_TAG, authAddress.publicKey, program)
            )
          )
        );

        return new Uint8Array(Buffer.from(pqLsigData.lsigSig, 'base64'));
      },
    };

    const addrWithSigners =
      addressWithSignersFromRawFalcon1024Signer(falconSigningKey);

    const lsigAccount = new LogicSigAccount(program);
    await lsigAccount.signWithSigner(addrWithSigners);

    assert.deepEqual(
      lsigAccount.lsig.pqsig!.sig,
      new Uint8Array(Buffer.from(pqLsigData.lsigSig, 'base64'))
    );

    const txn = decodeMsgpack(
      Buffer.from(pqLsigData.txnBlob, 'base64'),
      Transaction
    );

    const { blob } = await signTransactionWithSigner(
      txn,
      makeLogicSigAccountTransactionSigner(lsigAccount)
    );

    assert.deepEqual(
      blob,
      new Uint8Array(Buffer.from(pqLsigData.stxnBlob, 'base64'))
    );
  });
});
